---
title: "03a_model_build_logreg"
output: html_document
date: "2022-11-19"
---




libraries + setup
```{r}
rm(list=ls())
library(data.table)
library(dplyr)
library(nnet)
library(caret)
library(stringr)
library(pROC)
library(lubridate)
```

read in data
```{r}
input_date <- "14Jul24"
data <- readRDS(paste0("data/output/final_model_data_multiclass__",input_date,".rds")) %>%
        .[,.(outcome,home2away_delta_rankings,neutral,home2away_delta_goals_scored_last_9_matches
               ,home2away_delta_goals_conceded_last_9_matches,home_fifa_rank_change
               ,home2away_delta_ties_last_9_matches , home2away_delta_wins_last_9_matches
               ,away_team_wins_last_3_matches, home_team_goals_scored_last_3_matches
                ,home_team_wins_last_3_matches,tournament,away_fifa_rank_change,date)] %>%
        .[,friendly_flag := case_when(tournament=="Friendly" ~ 1,TRUE~0)]

```


```{r}
set.seed(31)

trainIndex <- createDataPartition(data$outcome,p=0.7,list=FALSE,times=1)
test <- data[-trainIndex]
train <- data[trainIndex]
```


```{r}
m1 <- multinom(outcome ~ 
               home2away_delta_rankings+neutral+home2away_delta_goals_scored_last_9_matches
               +home2away_delta_goals_conceded_last_9_matches+home_fifa_rank_change + home2away_delta_wins_last_9_matches
               +home_fifa_rank_change + away_fifa_rank_change + away_team_wins_last_3_matches 
               ,data=train)
m1 %>% summary()
```


```{r}


ti_aes <- function(){
  theme(
    panel.background = element_blank()
    ,panel.grid.major = element_blank()
    ,panel.grid.minor = element_blank()
    ,panel.border = element_rect(colour="black",fill=NA)
    ,axis.text = element_text(colour="black")
    ,strip.background = element_rect(color="#277150",fill="#277150")
    ,strip.text = element_text(color="#C8F0D8",size = 14,face="bold")
    ,axis.line = element_line(color="black")
    ,axis.ticks = element_line(color="black")
    ,axis.text=element_text(size=12)
    ,axis.title = element_text(color="#689885",size=14)
  )
}

# plot 1: feature importance
feat_plot <- m1 %>% 
  varImp() %>% 
  tibble::rownames_to_column() %>%
  mutate(Overall = Overall/sum(Overall))%>%
  mutate(label = paste0(round(Overall*100,2),"%"))%>%
  mutate(rowname=stringr::str_replace_all(rowname,"last_","l"))%>%
  mutate(rowname=stringr::str_replace_all(rowname,"_matches","m"))%>%
  mutate(rowname=stringr::str_replace_all(rowname,"home2away_",""))%>%
  mutate(rowname= fct_reorder(rowname,Overall))%>%
  ggplot()+
  geom_bar(stat="identity",aes(x=rowname,y=Overall),fill="#a2eacb")+
  geom_text(aes(x=rowname,y=Overall+0.1,label = label),colour = "#a2eacb",size=4)+
  scale_y_continuous(labels = scales::percent)+
  ti_aes()+
  theme(axis.text.x = element_text(angle=90))+
  coord_flip()+
  scale_y_continuous(labels = scales::percent,limits=c(0,1))+
  xlab("")+
  ylab("Relative Contribution")
  


predictions <- predict(m1,data,"probs") %>% 
  data.frame()%>%
  setDT() %>%
  cbind(outcome=data$outcome) %>%
  cbind(year=year(data$date)) %>%
  .[,`:=`(
    home_outcome = case_when(outcome=="home win"~1,TRUE~0)
    ,away_outcome = case_when(outcome=="away win"~1,TRUE~0)
    ,tie_outcome = case_when(outcome=="tie"~1,TRUE~0)
  )] %>%
  .[trainIndex,train_data:=1] %>%
  .[,train_data := coalesce(train_data,0)]%>%
  na.omit()%>%
  .[year>2008]


gini_tab <- rbind(
predictions[,.(away_gini=auc(away_outcome,away.win),home_gini=auc(home_outcome,home.win),tie_gini=auc(tie_outcome,tie)),year] %>% .[,cat:="all"]
,predictions[train_data==1]%>%.[,.(away_gini=auc(away_outcome,away.win),home_gini=auc(home_outcome,home.win),tie_gini=auc(tie_outcome,tie)),year] %>% .[,cat:="train"]
,predictions[train_data==0]%>%.[,.(away_gini=auc(away_outcome,away.win),home_gini=auc(home_outcome,home.win),tie_gini=auc(tie_outcome,tie)),year] %>% .[,cat:="test"]
)

cal <- rbind(
  predictions[,.(away_predicted=mean(away.win),away_actual=sum(away_outcome)/.N,away_vol=sum(away_outcome)
                      ,home_predicted=mean(home.win),home_actual=sum(home_outcome)/.N,home_vol=sum(home_outcome)
                      ,tie_predicted=mean(tie),tie_actual=sum(tie_outcome)/.N,tie_vol=sum(tie_outcome)
                      )]%>% .[,cat:="all"]
  ,predictions[train_data==1]%>%.[,.(away_predicted=mean(away.win),away_actual=sum(away_outcome)/.N,away_vol=sum(away_outcome)
                      ,home_predicted=mean(home.win),home_actual=sum(home_outcome)/.N,home_vol=sum(home_outcome)
                      ,tie_predicted=mean(tie),tie_actual=sum(tie_outcome)/.N,tie_vol=sum(tie_outcome)
                      )]%>% .[,cat:="train"]
  ,predictions[train_data==0]%>%.[,.(away_predicted=mean(away.win),away_actual=sum(away_outcome)/.N,away_vol=sum(away_outcome)
                      ,home_predicted=mean(home.win),home_actual=sum(home_outcome)/.N,home_vol=sum(home_outcome)
                      ,tie_predicted=mean(tie),tie_actual=sum(tie_outcome)/.N,tie_vol=sum(tie_outcome)
                      )]%>% .[,cat:="test"]
)

```



## export model object
```{r}
list(model =m1,feat_plot = feat_plot, gini_tab=gini_tab, cal=cal
     #,conf_train = tab_train,conf_test = tab_test,away_roc = away_roc,home_roc=home_roc,tie_roc=tie_roc
     )%>%
saveRDS(paste0("models/logreg_",input_date,".rds"))
```


